export type Difficulty = 'Easy' | 'Medium' | 'Hard'

export type NeetcodeProblem = {
  name: string
  category: string
  difficulty: Difficulty
  url: string
  leetcodeUrl: string
  slugs: string[]
}

export const NEETCODE_250: NeetcodeProblem[] = [
  {
    name: 'Concatenation of Array',
    category: 'Arrays & Hashing',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/concatenation-of-array?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/concatenation-of-array/',
    slugs: ['concatenation-of-array'],
  },
  {
    name: 'Contains Duplicate',
    category: 'Arrays & Hashing',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/duplicate-integer?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/contains-duplicate/',
    slugs: ['contains-duplicate', 'duplicate-integer'],
  },
  {
    name: 'Valid Anagram',
    category: 'Arrays & Hashing',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/is-anagram?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/valid-anagram/',
    slugs: ['is-anagram', 'valid-anagram'],
  },
  {
    name: 'Two Sum',
    category: 'Arrays & Hashing',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/two-integer-sum?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/two-sum/',
    slugs: ['two-integer-sum', 'two-sum'],
  },
  {
    name: 'Longest Common Prefix',
    category: 'Arrays & Hashing',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/longest-common-prefix?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/longest-common-prefix/',
    slugs: ['longest-common-prefix'],
  },
  {
    name: 'Group Anagrams',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/anagram-groups?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/group-anagrams/',
    slugs: ['anagram-groups', 'group-anagrams'],
  },
  {
    name: 'Remove Element',
    category: 'Arrays & Hashing',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/remove-element?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/remove-element/',
    slugs: ['remove-element'],
  },
  {
    name: 'Majority Element',
    category: 'Arrays & Hashing',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/majority-element?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/majority-element/',
    slugs: ['majority-element'],
  },
  {
    name: 'Design HashSet',
    category: 'Arrays & Hashing',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/design-hashset?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/design-hashset/',
    slugs: ['design-hashset'],
  },
  {
    name: 'Design HashMap',
    category: 'Arrays & Hashing',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/design-hashmap?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/design-hashmap/',
    slugs: ['design-hashmap'],
  },
  {
    name: 'Sort an Array',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/sort-an-array?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/sort-an-array/',
    slugs: ['sort-an-array'],
  },
  {
    name: 'Sort Colors',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/sort-colors?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/sort-colors/',
    slugs: ['sort-colors'],
  },
  {
    name: 'Top K Frequent Elements',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/top-k-elements-in-list?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-elements/',
    slugs: ['top-k-elements-in-list', 'top-k-frequent-elements'],
  },
  {
    name: 'Encode and Decode Strings',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/string-encode-and-decode?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/encode-and-decode-strings/',
    slugs: ['encode-and-decode-strings', 'string-encode-and-decode'],
  },
  {
    name: 'Range Sum Query 2D Immutable',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/range-sum-query-2d-immutable?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/range-sum-query-2d-immutable/',
    slugs: ['range-sum-query-2d-immutable'],
  },
  {
    name: 'Product of Array Except Self',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/products-of-array-discluding-self?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/product-of-array-except-self/',
    slugs: ['product-of-array-except-self', 'products-of-array-discluding-self'],
  },
  {
    name: 'Valid Sudoku',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/valid-sudoku?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/valid-sudoku/',
    slugs: ['valid-sudoku'],
  },
  {
    name: 'Longest Consecutive Sequence',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/longest-consecutive-sequence?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/longest-consecutive-sequence/',
    slugs: ['longest-consecutive-sequence'],
  },
  {
    name: 'Best Time to Buy And Sell Stock II',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/best-time-to-buy-and-sell-stock-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/',
    slugs: ['best-time-to-buy-and-sell-stock-ii'],
  },
  {
    name: 'Majority Element II',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/majority-element-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/majority-element-ii',
    slugs: ['majority-element-ii'],
  },
  {
    name: 'Subarray Sum Equals K',
    category: 'Arrays & Hashing',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/subarray-sum-equals-k?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/subarray-sum-equals-k/',
    slugs: ['subarray-sum-equals-k'],
  },
  {
    name: 'First Missing Positive',
    category: 'Arrays & Hashing',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/first-missing-positive?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/first-missing-positive/',
    slugs: ['first-missing-positive'],
  },
  {
    name: 'Reverse String',
    category: 'Two Pointers',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/reverse-string?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/reverse-string/',
    slugs: ['reverse-string'],
  },
  {
    name: 'Valid Palindrome',
    category: 'Two Pointers',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/is-palindrome?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/valid-palindrome/',
    slugs: ['is-palindrome', 'valid-palindrome'],
  },
  {
    name: 'Valid Palindrome II',
    category: 'Two Pointers',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/valid-palindrome-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/valid-palindrome-ii/',
    slugs: ['valid-palindrome-ii'],
  },
  {
    name: 'Merge Strings Alternately',
    category: 'Two Pointers',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/merge-strings-alternately?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/merge-strings-alternately/',
    slugs: ['merge-strings-alternately'],
  },
  {
    name: 'Merge Sorted Array',
    category: 'Two Pointers',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/merge-sorted-array?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/merge-sorted-array/',
    slugs: ['merge-sorted-array'],
  },
  {
    name: 'Remove Duplicates From Sorted Array',
    category: 'Two Pointers',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/remove-duplicates-from-sorted-array?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/',
    slugs: ['remove-duplicates-from-sorted-array'],
  },
  {
    name: 'Two Sum II Input Array Is Sorted',
    category: 'Two Pointers',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/two-integer-sum-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
    slugs: ['two-integer-sum-ii', 'two-sum-ii-input-array-is-sorted'],
  },
  {
    name: '3Sum',
    category: 'Two Pointers',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/three-integer-sum?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/3sum/',
    slugs: ['3sum', 'three-integer-sum'],
  },
  {
    name: '4Sum',
    category: 'Two Pointers',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/4sum?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/4sum/',
    slugs: ['4sum'],
  },
  {
    name: 'Rotate Array',
    category: 'Two Pointers',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/rotate-array?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/rotate-array/',
    slugs: ['rotate-array'],
  },
  {
    name: 'Container With Most Water',
    category: 'Two Pointers',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/max-water-container?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/container-with-most-water/',
    slugs: ['container-with-most-water', 'max-water-container'],
  },
  {
    name: 'Boats to Save People',
    category: 'Two Pointers',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/boats-to-save-people?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/boats-to-save-people/',
    slugs: ['boats-to-save-people'],
  },
  {
    name: 'Trapping Rain Water',
    category: 'Two Pointers',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/trapping-rain-water?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/trapping-rain-water/',
    slugs: ['trapping-rain-water'],
  },
  {
    name: 'Contains Duplicate II',
    category: 'Sliding Window',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/contains-duplicate-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/contains-duplicate-ii/',
    slugs: ['contains-duplicate-ii'],
  },
  {
    name: 'Best Time to Buy And Sell Stock',
    category: 'Sliding Window',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/buy-and-sell-crypto?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
    slugs: ['best-time-to-buy-and-sell-stock', 'buy-and-sell-crypto'],
  },
  {
    name: 'Longest Substring Without Repeating Characters',
    category: 'Sliding Window',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/longest-substring-without-duplicates?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    slugs: ['longest-substring-without-duplicates', 'longest-substring-without-repeating-characters'],
  },
  {
    name: 'Longest Repeating Character Replacement',
    category: 'Sliding Window',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/longest-repeating-substring-with-replacement?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
    slugs: ['longest-repeating-character-replacement', 'longest-repeating-substring-with-replacement'],
  },
  {
    name: 'Permutation In String',
    category: 'Sliding Window',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/permutation-string?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/permutation-in-string/',
    slugs: ['permutation-in-string', 'permutation-string'],
  },
  {
    name: 'Minimum Size Subarray Sum',
    category: 'Sliding Window',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/minimum-size-subarray-sum?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/minimum-size-subarray-sum/',
    slugs: ['minimum-size-subarray-sum'],
  },
  {
    name: 'Find K Closest Elements',
    category: 'Sliding Window',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/find-k-closest-elements?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/find-k-closest-elements/',
    slugs: ['find-k-closest-elements'],
  },
  {
    name: 'Minimum Window Substring',
    category: 'Sliding Window',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/minimum-window-with-characters?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/minimum-window-substring/',
    slugs: ['minimum-window-substring', 'minimum-window-with-characters'],
  },
  {
    name: 'Sliding Window Maximum',
    category: 'Sliding Window',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/sliding-window-maximum?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/sliding-window-maximum/',
    slugs: ['sliding-window-maximum'],
  },
  {
    name: 'Baseball Game',
    category: 'Stack',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/baseball-game?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/baseball-game/',
    slugs: ['baseball-game'],
  },
  {
    name: 'Valid Parentheses',
    category: 'Stack',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/validate-parentheses?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/valid-parentheses/',
    slugs: ['valid-parentheses', 'validate-parentheses'],
  },
  {
    name: 'Implement Stack Using Queues',
    category: 'Stack',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/implement-stack-using-queues?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/implement-stack-using-queues/',
    slugs: ['implement-stack-using-queues'],
  },
  {
    name: 'Implement Queue using Stacks',
    category: 'Stack',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/implement-queue-using-stacks?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/implement-queue-using-stacks',
    slugs: ['implement-queue-using-stacks'],
  },
  {
    name: 'Min Stack',
    category: 'Stack',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/minimum-stack?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/min-stack/',
    slugs: ['min-stack', 'minimum-stack'],
  },
  {
    name: 'Evaluate Reverse Polish Notation',
    category: 'Stack',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/evaluate-reverse-polish-notation?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
    slugs: ['evaluate-reverse-polish-notation'],
  },
  {
    name: 'Generate Parentheses',
    category: 'Stack',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/generate-parentheses?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/generate-parentheses/',
    slugs: ['generate-parentheses'],
  },
  {
    name: 'Asteroid Collision',
    category: 'Stack',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/asteroid-collision?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/asteroid-collision/',
    slugs: ['asteroid-collision'],
  },
  {
    name: 'Daily Temperatures',
    category: 'Stack',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/daily-temperatures?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/daily-temperatures/',
    slugs: ['daily-temperatures'],
  },
  {
    name: 'Online Stock Span',
    category: 'Stack',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/online-stock-span?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/online-stock-span/',
    slugs: ['online-stock-span'],
  },
  {
    name: 'Car Fleet',
    category: 'Stack',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/car-fleet?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/car-fleet/',
    slugs: ['car-fleet'],
  },
  {
    name: 'Simplify Path',
    category: 'Stack',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/simplify-path?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/simplify-path/',
    slugs: ['simplify-path'],
  },
  {
    name: 'Decode String',
    category: 'Stack',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/decode-string?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/decode-string/',
    slugs: ['decode-string'],
  },
  {
    name: 'Maximum Frequency Stack',
    category: 'Stack',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/maximum-frequency-stack?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/maximum-frequency-stack/',
    slugs: ['maximum-frequency-stack'],
  },
  {
    name: 'Largest Rectangle In Histogram',
    category: 'Stack',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/largest-rectangle-in-histogram?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
    slugs: ['largest-rectangle-in-histogram'],
  },
  {
    name: 'Binary Search',
    category: 'Binary Search',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/binary-search?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/binary-search/',
    slugs: ['binary-search'],
  },
  {
    name: 'Search Insert Position',
    category: 'Binary Search',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/search-insert-position?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/search-insert-position/',
    slugs: ['search-insert-position'],
  },
  {
    name: 'Guess Number Higher Or Lower',
    category: 'Binary Search',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/guess-number-higher-or-lower?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/guess-number-higher-or-lower/',
    slugs: ['guess-number-higher-or-lower'],
  },
  {
    name: 'Sqrt(x)',
    category: 'Binary Search',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/sqrtx?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/sqrtx/',
    slugs: ['sqrtx'],
  },
  {
    name: 'Search a 2D Matrix',
    category: 'Binary Search',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/search-2d-matrix?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/search-a-2d-matrix/',
    slugs: ['search-2d-matrix', 'search-a-2d-matrix'],
  },
  {
    name: 'Koko Eating Bananas',
    category: 'Binary Search',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/eating-bananas?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/koko-eating-bananas/',
    slugs: ['eating-bananas', 'koko-eating-bananas'],
  },
  {
    name: 'Capacity to Ship Packages Within D Days',
    category: 'Binary Search',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/capacity-to-ship-packages-within-d-days?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/',
    slugs: ['capacity-to-ship-packages-within-d-days'],
  },
  {
    name: 'Find Minimum In Rotated Sorted Array',
    category: 'Binary Search',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/find-minimum-in-rotated-sorted-array?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
    slugs: ['find-minimum-in-rotated-sorted-array'],
  },
  {
    name: 'Search In Rotated Sorted Array',
    category: 'Binary Search',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/find-target-in-rotated-sorted-array?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
    slugs: ['find-target-in-rotated-sorted-array', 'search-in-rotated-sorted-array'],
  },
  {
    name: 'Search In Rotated Sorted Array II',
    category: 'Binary Search',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/search-in-rotated-sorted-array-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/',
    slugs: ['search-in-rotated-sorted-array-ii'],
  },
  {
    name: 'Time Based Key Value Store',
    category: 'Binary Search',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/time-based-key-value-store?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/time-based-key-value-store/',
    slugs: ['time-based-key-value-store'],
  },
  {
    name: 'Split Array Largest Sum',
    category: 'Binary Search',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/split-array-largest-sum?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/split-array-largest-sum/',
    slugs: ['split-array-largest-sum'],
  },
  {
    name: 'Median of Two Sorted Arrays',
    category: 'Binary Search',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/median-of-two-sorted-arrays?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
    slugs: ['median-of-two-sorted-arrays'],
  },
  {
    name: 'Find in Mountain Array',
    category: 'Binary Search',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/find-in-mountain-array?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/find-in-mountain-array',
    slugs: ['find-in-mountain-array'],
  },
  {
    name: 'Reverse Linked List',
    category: 'Linked List',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/reverse-a-linked-list?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/reverse-linked-list/',
    slugs: ['reverse-a-linked-list', 'reverse-linked-list'],
  },
  {
    name: 'Merge Two Sorted Lists',
    category: 'Linked List',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/merge-two-sorted-linked-lists?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/merge-two-sorted-lists/',
    slugs: ['merge-two-sorted-linked-lists', 'merge-two-sorted-lists'],
  },
  {
    name: 'Linked List Cycle',
    category: 'Linked List',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/linked-list-cycle-detection?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/linked-list-cycle/',
    slugs: ['linked-list-cycle', 'linked-list-cycle-detection'],
  },
  {
    name: 'Reorder List',
    category: 'Linked List',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/reorder-linked-list?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/reorder-list/',
    slugs: ['reorder-linked-list', 'reorder-list'],
  },
  {
    name: 'Remove Nth Node From End of List',
    category: 'Linked List',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/remove-node-from-end-of-linked-list?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
    slugs: ['remove-node-from-end-of-linked-list', 'remove-nth-node-from-end-of-list'],
  },
  {
    name: 'Copy List With Random Pointer',
    category: 'Linked List',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/copy-linked-list-with-random-pointer?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/copy-list-with-random-pointer/',
    slugs: ['copy-linked-list-with-random-pointer', 'copy-list-with-random-pointer'],
  },
  {
    name: 'Add Two Numbers',
    category: 'Linked List',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/add-two-numbers?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/add-two-numbers/',
    slugs: ['add-two-numbers'],
  },
  {
    name: 'Find The Duplicate Number',
    category: 'Linked List',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/find-duplicate-integer?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/find-the-duplicate-number/',
    slugs: ['find-duplicate-integer', 'find-the-duplicate-number'],
  },
  {
    name: 'Reverse Linked List II',
    category: 'Linked List',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/reverse-linked-list-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/reverse-linked-list-ii/',
    slugs: ['reverse-linked-list-ii'],
  },
  {
    name: 'Design Circular Queue',
    category: 'Linked List',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/design-circular-queue?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/design-circular-queue/',
    slugs: ['design-circular-queue'],
  },
  {
    name: 'LRU Cache',
    category: 'Linked List',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/lru-cache?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/lru-cache/',
    slugs: ['lru-cache'],
  },
  {
    name: 'LFU Cache',
    category: 'Linked List',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/lfu-cache?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/lfu-cache/',
    slugs: ['lfu-cache'],
  },
  {
    name: 'Merge K Sorted Lists',
    category: 'Linked List',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/merge-k-sorted-linked-lists?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/merge-k-sorted-lists/',
    slugs: ['merge-k-sorted-linked-lists', 'merge-k-sorted-lists'],
  },
  {
    name: 'Reverse Nodes In K Group',
    category: 'Linked List',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/reverse-nodes-in-k-group?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/reverse-nodes-in-k-group/',
    slugs: ['reverse-nodes-in-k-group'],
  },
  {
    name: 'Binary Tree Inorder Traversal',
    category: 'Trees',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/binary-tree-inorder-traversal?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/binary-tree-inorder-traversal/',
    slugs: ['binary-tree-inorder-traversal'],
  },
  {
    name: 'Binary Tree Preorder Traversal',
    category: 'Trees',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/binary-tree-preorder-traversal?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/binary-tree-preorder-traversal/',
    slugs: ['binary-tree-preorder-traversal'],
  },
  {
    name: 'Binary Tree Postorder Traversal',
    category: 'Trees',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/binary-tree-postorder-traversal?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/binary-tree-postorder-traversal/',
    slugs: ['binary-tree-postorder-traversal'],
  },
  {
    name: 'Invert Binary Tree',
    category: 'Trees',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/invert-a-binary-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/invert-binary-tree/',
    slugs: ['invert-a-binary-tree', 'invert-binary-tree'],
  },
  {
    name: 'Maximum Depth of Binary Tree',
    category: 'Trees',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/depth-of-binary-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
    slugs: ['depth-of-binary-tree', 'maximum-depth-of-binary-tree'],
  },
  {
    name: 'Diameter of Binary Tree',
    category: 'Trees',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/binary-tree-diameter?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/diameter-of-binary-tree/',
    slugs: ['binary-tree-diameter', 'diameter-of-binary-tree'],
  },
  {
    name: 'Balanced Binary Tree',
    category: 'Trees',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/balanced-binary-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/balanced-binary-tree/',
    slugs: ['balanced-binary-tree'],
  },
  {
    name: 'Same Tree',
    category: 'Trees',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/same-binary-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/same-tree/',
    slugs: ['same-binary-tree', 'same-tree'],
  },
  {
    name: 'Subtree of Another Tree',
    category: 'Trees',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/subtree-of-a-binary-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/subtree-of-another-tree/',
    slugs: ['subtree-of-a-binary-tree', 'subtree-of-another-tree'],
  },
  {
    name: 'Lowest Common Ancestor of a Binary Search Tree',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/lowest-common-ancestor-in-binary-search-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
    slugs: ['lowest-common-ancestor-in-binary-search-tree', 'lowest-common-ancestor-of-a-binary-search-tree'],
  },
  {
    name: 'Insert into a Binary Search Tree',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/insert-into-a-binary-search-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/insert-into-a-binary-search-tree/',
    slugs: ['insert-into-a-binary-search-tree'],
  },
  {
    name: 'Delete Node in a BST',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/delete-node-in-a-bst?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/delete-node-in-a-bst/',
    slugs: ['delete-node-in-a-bst'],
  },
  {
    name: 'Binary Tree Level Order Traversal',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/level-order-traversal-of-binary-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
    slugs: ['binary-tree-level-order-traversal', 'level-order-traversal-of-binary-tree'],
  },
  {
    name: 'Binary Tree Right Side View',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/binary-tree-right-side-view?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/binary-tree-right-side-view/',
    slugs: ['binary-tree-right-side-view'],
  },
  {
    name: 'Construct Quad Tree',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/construct-quad-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/construct-quad-tree/',
    slugs: ['construct-quad-tree'],
  },
  {
    name: 'Count Good Nodes In Binary Tree',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/count-good-nodes-in-binary-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/',
    slugs: ['count-good-nodes-in-binary-tree'],
  },
  {
    name: 'Validate Binary Search Tree',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/valid-binary-search-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/validate-binary-search-tree/',
    slugs: ['valid-binary-search-tree', 'validate-binary-search-tree'],
  },
  {
    name: 'Kth Smallest Element In a Bst',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/kth-smallest-integer-in-bst?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
    slugs: ['kth-smallest-element-in-a-bst', 'kth-smallest-integer-in-bst'],
  },
  {
    name: 'Construct Binary Tree From Preorder And Inorder Traversal',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/binary-tree-from-preorder-and-inorder-traversal?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
    slugs: ['binary-tree-from-preorder-and-inorder-traversal', 'construct-binary-tree-from-preorder-and-inorder-traversal'],
  },
  {
    name: 'House Robber III',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/house-robber-iii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/house-robber-iii/',
    slugs: ['house-robber-iii'],
  },
  {
    name: 'Delete Leaves With a Given Value',
    category: 'Trees',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/delete-leaves-with-a-given-value?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/delete-leaves-with-a-given-value',
    slugs: ['delete-leaves-with-a-given-value'],
  },
  {
    name: 'Binary Tree Maximum Path Sum',
    category: 'Trees',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/binary-tree-maximum-path-sum?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
    slugs: ['binary-tree-maximum-path-sum'],
  },
  {
    name: 'Serialize And Deserialize Binary Tree',
    category: 'Trees',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/serialize-and-deserialize-binary-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
    slugs: ['serialize-and-deserialize-binary-tree'],
  },
  {
    name: 'Kth Largest Element In a Stream',
    category: 'Heap / Priority Queue',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/kth-largest-integer-in-a-stream?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/',
    slugs: ['kth-largest-element-in-a-stream', 'kth-largest-integer-in-a-stream'],
  },
  {
    name: 'Last Stone Weight',
    category: 'Heap / Priority Queue',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/last-stone-weight?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/last-stone-weight/',
    slugs: ['last-stone-weight'],
  },
  {
    name: 'K Closest Points to Origin',
    category: 'Heap / Priority Queue',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/k-closest-points-to-origin?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/k-closest-points-to-origin/',
    slugs: ['k-closest-points-to-origin'],
  },
  {
    name: 'Kth Largest Element In An Array',
    category: 'Heap / Priority Queue',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/kth-largest-element-in-an-array?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
    slugs: ['kth-largest-element-in-an-array'],
  },
  {
    name: 'Task Scheduler',
    category: 'Heap / Priority Queue',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/task-scheduling?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/task-scheduler/',
    slugs: ['task-scheduler', 'task-scheduling'],
  },
  {
    name: 'Design Twitter',
    category: 'Heap / Priority Queue',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/design-twitter-feed?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/design-twitter/',
    slugs: ['design-twitter', 'design-twitter-feed'],
  },
  {
    name: 'Single Threaded CPU',
    category: 'Heap / Priority Queue',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/single-threaded-cpu?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/single-threaded-cpu/',
    slugs: ['single-threaded-cpu'],
  },
  {
    name: 'Reorganize String',
    category: 'Heap / Priority Queue',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/reorganize-string?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/reorganize-string/',
    slugs: ['reorganize-string'],
  },
  {
    name: 'Longest Happy String',
    category: 'Heap / Priority Queue',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/longest-happy-string?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/longest-happy-string/',
    slugs: ['longest-happy-string'],
  },
  {
    name: 'Car Pooling',
    category: 'Heap / Priority Queue',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/car-pooling?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/car-pooling/',
    slugs: ['car-pooling'],
  },
  {
    name: 'Find Median From Data Stream',
    category: 'Heap / Priority Queue',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/find-median-in-a-data-stream?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/find-median-from-data-stream/',
    slugs: ['find-median-from-data-stream', 'find-median-in-a-data-stream'],
  },
  {
    name: 'IPO',
    category: 'Heap / Priority Queue',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/ipo?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/ipo/',
    slugs: ['ipo'],
  },
  {
    name: 'Sum of All Subsets XOR Total',
    category: 'Backtracking',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/sum-of-all-subset-xor-totals?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/sum-of-all-subset-xor-totals',
    slugs: ['sum-of-all-subset-xor-totals'],
  },
  {
    name: 'Subsets',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/subsets?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/subsets/',
    slugs: ['subsets'],
  },
  {
    name: 'Combination Sum',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/combination-target-sum?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/combination-sum/',
    slugs: ['combination-sum', 'combination-target-sum'],
  },
  {
    name: 'Combination Sum II',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/combination-target-sum-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/combination-sum-ii/',
    slugs: ['combination-sum-ii', 'combination-target-sum-ii'],
  },
  {
    name: 'Combinations',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/combinations?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/combinations/',
    slugs: ['combinations'],
  },
  {
    name: 'Permutations',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/permutations?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/permutations/',
    slugs: ['permutations'],
  },
  {
    name: 'Subsets II',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/subsets-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/subsets-ii/',
    slugs: ['subsets-ii'],
  },
  {
    name: 'Permutations II',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/permutations-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/permutations-ii/',
    slugs: ['permutations-ii'],
  },
  {
    name: 'Word Search',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/search-for-word?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/word-search/',
    slugs: ['search-for-word', 'word-search'],
  },
  {
    name: 'Palindrome Partitioning',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/palindrome-partitioning?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/palindrome-partitioning/',
    slugs: ['palindrome-partitioning'],
  },
  {
    name: 'Letter Combinations of a Phone Number',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/combinations-of-a-phone-number?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
    slugs: ['combinations-of-a-phone-number', 'letter-combinations-of-a-phone-number'],
  },
  {
    name: 'Matchsticks to Square',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/matchsticks-to-square?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/matchsticks-to-square/',
    slugs: ['matchsticks-to-square'],
  },
  {
    name: 'Partition to K Equal Sum Subsets',
    category: 'Backtracking',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/partition-to-k-equal-sum-subsets?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/partition-to-k-equal-sum-subsets/',
    slugs: ['partition-to-k-equal-sum-subsets'],
  },
  {
    name: 'N Queens',
    category: 'Backtracking',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/n-queens?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/n-queens/',
    slugs: ['n-queens'],
  },
  {
    name: 'N Queens II',
    category: 'Backtracking',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/n-queens-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/n-queens-ii/',
    slugs: ['n-queens-ii'],
  },
  {
    name: 'Word Break II',
    category: 'Backtracking',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/word-break-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/word-break-ii',
    slugs: ['word-break-ii'],
  },
  {
    name: 'Implement Trie Prefix Tree',
    category: 'Tries',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/implement-prefix-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
    slugs: ['implement-prefix-tree', 'implement-trie-prefix-tree'],
  },
  {
    name: 'Design Add And Search Words Data Structure',
    category: 'Tries',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/design-word-search-data-structure?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/',
    slugs: ['design-add-and-search-words-data-structure', 'design-word-search-data-structure'],
  },
  {
    name: 'Extra Characters in a String',
    category: 'Tries',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/extra-characters-in-a-string?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/extra-characters-in-a-string/',
    slugs: ['extra-characters-in-a-string'],
  },
  {
    name: 'Word Search II',
    category: 'Tries',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/search-for-word-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/word-search-ii/',
    slugs: ['search-for-word-ii', 'word-search-ii'],
  },
  {
    name: 'Island Perimeter',
    category: 'Graphs',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/island-perimeter?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/island-perimeter/',
    slugs: ['island-perimeter'],
  },
  {
    name: 'Verifying An Alien Dictionary',
    category: 'Graphs',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/verifying-an-alien-dictionary?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/verifying-an-alien-dictionary/',
    slugs: ['verifying-an-alien-dictionary'],
  },
  {
    name: 'Find the Town Judge',
    category: 'Graphs',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/find-the-town-judge?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/find-the-town-judge',
    slugs: ['find-the-town-judge'],
  },
  {
    name: 'Number of Islands',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/count-number-of-islands?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/number-of-islands/',
    slugs: ['count-number-of-islands', 'number-of-islands'],
  },
  {
    name: 'Max Area of Island',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/max-area-of-island?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/max-area-of-island/',
    slugs: ['max-area-of-island'],
  },
  {
    name: 'Clone Graph',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/clone-graph?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/clone-graph/',
    slugs: ['clone-graph'],
  },
  {
    name: 'Walls And Gates',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/islands-and-treasure?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/walls-and-gates/',
    slugs: ['islands-and-treasure', 'walls-and-gates'],
  },
  {
    name: 'Rotting Oranges',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/rotting-fruit?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/rotting-oranges/',
    slugs: ['rotting-fruit', 'rotting-oranges'],
  },
  {
    name: 'Pacific Atlantic Water Flow',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/pacific-atlantic-water-flow?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
    slugs: ['pacific-atlantic-water-flow'],
  },
  {
    name: 'Surrounded Regions',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/surrounded-regions?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/surrounded-regions/',
    slugs: ['surrounded-regions'],
  },
  {
    name: 'Open The Lock',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/open-the-lock?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/open-the-lock/',
    slugs: ['open-the-lock'],
  },
  {
    name: 'Course Schedule',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/course-schedule?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/course-schedule/',
    slugs: ['course-schedule'],
  },
  {
    name: 'Course Schedule II',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/course-schedule-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/course-schedule-ii/',
    slugs: ['course-schedule-ii'],
  },
  {
    name: 'Graph Valid Tree',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/valid-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/graph-valid-tree/',
    slugs: ['graph-valid-tree', 'valid-tree'],
  },
  {
    name: 'Course Schedule IV',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/course-schedule-iv?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/course-schedule-iv/',
    slugs: ['course-schedule-iv'],
  },
  {
    name: 'Number of Connected Components In An Undirected Graph',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/count-connected-components?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/',
    slugs: ['count-connected-components', 'number-of-connected-components-in-an-undirected-graph'],
  },
  {
    name: 'Redundant Connection',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/redundant-connection?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/redundant-connection/',
    slugs: ['redundant-connection'],
  },
  {
    name: 'Accounts Merge',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/accounts-merge?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/accounts-merge/',
    slugs: ['accounts-merge'],
  },
  {
    name: 'Evaluate Division',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/evaluate-division?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/evaluate-division/',
    slugs: ['evaluate-division'],
  },
  {
    name: 'Minimum Height Trees',
    category: 'Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/minimum-height-trees?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/minimum-height-trees',
    slugs: ['minimum-height-trees'],
  },
  {
    name: 'Word Ladder',
    category: 'Graphs',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/word-ladder?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/word-ladder/',
    slugs: ['word-ladder'],
  },
  {
    name: 'Path with Minimum Effort',
    category: 'Advanced Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/path-with-minimum-effort?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/path-with-minimum-effort/',
    slugs: ['path-with-minimum-effort'],
  },
  {
    name: 'Network Delay Time',
    category: 'Advanced Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/network-delay-time?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/network-delay-time/',
    slugs: ['network-delay-time'],
  },
  {
    name: 'Reconstruct Itinerary',
    category: 'Advanced Graphs',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/reconstruct-flight-path?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/reconstruct-itinerary/',
    slugs: ['reconstruct-flight-path', 'reconstruct-itinerary'],
  },
  {
    name: 'Min Cost to Connect All Points',
    category: 'Advanced Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/min-cost-to-connect-points?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/min-cost-to-connect-all-points/',
    slugs: ['min-cost-to-connect-all-points', 'min-cost-to-connect-points'],
  },
  {
    name: 'Swim In Rising Water',
    category: 'Advanced Graphs',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/swim-in-rising-water?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/swim-in-rising-water/',
    slugs: ['swim-in-rising-water'],
  },
  {
    name: 'Alien Dictionary',
    category: 'Advanced Graphs',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/foreign-dictionary?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/alien-dictionary/',
    slugs: ['alien-dictionary', 'foreign-dictionary'],
  },
  {
    name: 'Cheapest Flights Within K Stops',
    category: 'Advanced Graphs',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/cheapest-flight-path?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
    slugs: ['cheapest-flight-path', 'cheapest-flights-within-k-stops'],
  },
  {
    name: 'Find Critical and Pseudo Critical Edges in Minimum Spanning Tree',
    category: 'Advanced Graphs',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/',
    slugs: ['find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree'],
  },
  {
    name: 'Build a Matrix With Conditions',
    category: 'Advanced Graphs',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/build-a-matrix-with-conditions?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/build-a-matrix-with-conditions',
    slugs: ['build-a-matrix-with-conditions'],
  },
  {
    name: 'Greatest Common Divisor Traversal',
    category: 'Advanced Graphs',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/greatest-common-divisor-traversal?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/greatest-common-divisor-traversal',
    slugs: ['greatest-common-divisor-traversal'],
  },
  {
    name: 'Climbing Stairs',
    category: '1-D Dynamic Programming',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/climbing-stairs?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/climbing-stairs/',
    slugs: ['climbing-stairs'],
  },
  {
    name: 'Min Cost Climbing Stairs',
    category: '1-D Dynamic Programming',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/min-cost-climbing-stairs?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/min-cost-climbing-stairs/',
    slugs: ['min-cost-climbing-stairs'],
  },
  {
    name: 'N-th Tribonacci Number',
    category: '1-D Dynamic Programming',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/n-th-tribonacci-number?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/n-th-tribonacci-number/',
    slugs: ['n-th-tribonacci-number'],
  },
  {
    name: 'House Robber',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/house-robber?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/house-robber/',
    slugs: ['house-robber'],
  },
  {
    name: 'House Robber II',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/house-robber-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/house-robber-ii/',
    slugs: ['house-robber-ii'],
  },
  {
    name: 'Longest Palindromic Substring',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/longest-palindromic-substring?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/longest-palindromic-substring/',
    slugs: ['longest-palindromic-substring'],
  },
  {
    name: 'Palindromic Substrings',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/palindromic-substrings?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/palindromic-substrings/',
    slugs: ['palindromic-substrings'],
  },
  {
    name: 'Decode Ways',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/decode-ways?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/decode-ways/',
    slugs: ['decode-ways'],
  },
  {
    name: 'Coin Change',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/coin-change?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/coin-change/',
    slugs: ['coin-change'],
  },
  {
    name: 'Maximum Product Subarray',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/maximum-product-subarray?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/maximum-product-subarray/',
    slugs: ['maximum-product-subarray'],
  },
  {
    name: 'Word Break',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/word-break?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/word-break/',
    slugs: ['word-break'],
  },
  {
    name: 'Longest Increasing Subsequence',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/longest-increasing-subsequence?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-subsequence/',
    slugs: ['longest-increasing-subsequence'],
  },
  {
    name: 'Partition Equal Subset Sum',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/partition-equal-subset-sum?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/partition-equal-subset-sum/',
    slugs: ['partition-equal-subset-sum'],
  },
  {
    name: 'Combination Sum IV',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/combination-sum-iv?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/combination-sum-iv/',
    slugs: ['combination-sum-iv'],
  },
  {
    name: 'Perfect Squares',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/perfect-squares?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/perfect-squares/',
    slugs: ['perfect-squares'],
  },
  {
    name: 'Integer Break',
    category: '1-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/integer-break?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/integer-break/',
    slugs: ['integer-break'],
  },
  {
    name: 'Stone Game III',
    category: '1-D Dynamic Programming',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/stone-game-iii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/stone-game-iii/',
    slugs: ['stone-game-iii'],
  },
  {
    name: 'Unique Paths',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/count-paths?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/unique-paths/',
    slugs: ['count-paths', 'unique-paths'],
  },
  {
    name: 'Unique Paths II',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/unique-paths-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/unique-paths-ii/',
    slugs: ['unique-paths-ii'],
  },
  {
    name: 'Minimum Path Sum',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/minimum-path-sum?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/minimum-path-sum/',
    slugs: ['minimum-path-sum'],
  },
  {
    name: 'Longest Common Subsequence',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/longest-common-subsequence?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/longest-common-subsequence/',
    slugs: ['longest-common-subsequence'],
  },
  {
    name: 'Last Stone Weight II',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/last-stone-weight-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/last-stone-weight-ii/',
    slugs: ['last-stone-weight-ii'],
  },
  {
    name: 'Best Time to Buy And Sell Stock With Cooldown',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/buy-and-sell-crypto-with-cooldown?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/',
    slugs: ['best-time-to-buy-and-sell-stock-with-cooldown', 'buy-and-sell-crypto-with-cooldown'],
  },
  {
    name: 'Coin Change II',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/coin-change-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/coin-change-ii/',
    slugs: ['coin-change-ii'],
  },
  {
    name: 'Target Sum',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/target-sum?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/target-sum/',
    slugs: ['target-sum'],
  },
  {
    name: 'Interleaving String',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/interleaving-string?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/interleaving-string/',
    slugs: ['interleaving-string'],
  },
  {
    name: 'Stone Game',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/stone-game?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/stone-game/',
    slugs: ['stone-game'],
  },
  {
    name: 'Stone Game II',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/stone-game-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/stone-game-ii/',
    slugs: ['stone-game-ii'],
  },
  {
    name: 'Longest Increasing Path In a Matrix',
    category: '2-D Dynamic Programming',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/longest-increasing-path-in-matrix?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/',
    slugs: ['longest-increasing-path-in-a-matrix', 'longest-increasing-path-in-matrix'],
  },
  {
    name: 'Distinct Subsequences',
    category: '2-D Dynamic Programming',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/count-subsequences?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/distinct-subsequences/',
    slugs: ['count-subsequences', 'distinct-subsequences'],
  },
  {
    name: 'Edit Distance',
    category: '2-D Dynamic Programming',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/edit-distance?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/edit-distance/',
    slugs: ['edit-distance'],
  },
  {
    name: 'Burst Balloons',
    category: '2-D Dynamic Programming',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/burst-balloons?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/burst-balloons/',
    slugs: ['burst-balloons'],
  },
  {
    name: 'Regular Expression Matching',
    category: '2-D Dynamic Programming',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/regular-expression-matching?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/regular-expression-matching/',
    slugs: ['regular-expression-matching'],
  },
  {
    name: 'Lemonade Change',
    category: 'Greedy',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/lemonade-change?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/lemonade-change/',
    slugs: ['lemonade-change'],
  },
  {
    name: 'Maximum Subarray',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/maximum-subarray?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/maximum-subarray/',
    slugs: ['maximum-subarray'],
  },
  {
    name: 'Maximum Sum Circular Subarray',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/maximum-sum-circular-subarray?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/maximum-sum-circular-subarray/',
    slugs: ['maximum-sum-circular-subarray'],
  },
  {
    name: 'Longest Turbulent Subarray',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/longest-turbulent-subarray?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/longest-turbulent-subarray/',
    slugs: ['longest-turbulent-subarray'],
  },
  {
    name: 'Jump Game',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/jump-game?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/jump-game/',
    slugs: ['jump-game'],
  },
  {
    name: 'Jump Game II',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/jump-game-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/jump-game-ii/',
    slugs: ['jump-game-ii'],
  },
  {
    name: 'Jump Game VII',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/jump-game-vii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/jump-game-vii/',
    slugs: ['jump-game-vii'],
  },
  {
    name: 'Gas Station',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/gas-station?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/gas-station/',
    slugs: ['gas-station'],
  },
  {
    name: 'Hand of Straights',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/hand-of-straights?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/hand-of-straights/',
    slugs: ['hand-of-straights'],
  },
  {
    name: 'Dota2 Senate',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/dota2-senate?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/dota2-senate/',
    slugs: ['dota2-senate'],
  },
  {
    name: 'Merge Triplets to Form Target Triplet',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/merge-triplets-to-form-target?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/',
    slugs: ['merge-triplets-to-form-target', 'merge-triplets-to-form-target-triplet'],
  },
  {
    name: 'Partition Labels',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/partition-labels?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/partition-labels/',
    slugs: ['partition-labels'],
  },
  {
    name: 'Valid Parenthesis String',
    category: 'Greedy',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/valid-parenthesis-string?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/valid-parenthesis-string/',
    slugs: ['valid-parenthesis-string'],
  },
  {
    name: 'Candy',
    category: 'Greedy',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/candy?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/candy/',
    slugs: ['candy'],
  },
  {
    name: 'Insert Interval',
    category: 'Intervals',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/insert-new-interval?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/insert-interval/',
    slugs: ['insert-interval', 'insert-new-interval'],
  },
  {
    name: 'Merge Intervals',
    category: 'Intervals',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/merge-intervals?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/merge-intervals/',
    slugs: ['merge-intervals'],
  },
  {
    name: 'Non Overlapping Intervals',
    category: 'Intervals',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/non-overlapping-intervals?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/non-overlapping-intervals/',
    slugs: ['non-overlapping-intervals'],
  },
  {
    name: 'Meeting Rooms',
    category: 'Intervals',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/meeting-schedule?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/meeting-rooms/',
    slugs: ['meeting-rooms', 'meeting-schedule'],
  },
  {
    name: 'Meeting Rooms II',
    category: 'Intervals',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/meeting-schedule-ii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/meeting-rooms-ii/',
    slugs: ['meeting-rooms-ii', 'meeting-schedule-ii'],
  },
  {
    name: 'Meeting Rooms III',
    category: 'Intervals',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/meeting-rooms-iii?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/meeting-rooms-iii',
    slugs: ['meeting-rooms-iii'],
  },
  {
    name: 'Minimum Interval to Include Each Query',
    category: 'Intervals',
    difficulty: 'Hard',
    url: 'https://neetcode.io/problems/minimum-interval-including-query?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/minimum-interval-to-include-each-query/',
    slugs: ['minimum-interval-including-query', 'minimum-interval-to-include-each-query'],
  },
  {
    name: 'Excel Sheet Column Title',
    category: 'Math & Geometry',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/excel-sheet-column-title?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/excel-sheet-column-title/',
    slugs: ['excel-sheet-column-title'],
  },
  {
    name: 'Greatest Common Divisor of Strings',
    category: 'Math & Geometry',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/greatest-common-divisor-of-strings?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/greatest-common-divisor-of-strings/',
    slugs: ['greatest-common-divisor-of-strings'],
  },
  {
    name: 'Insert Greatest Common Divisors in Linked List',
    category: 'Math & Geometry',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/insert-greatest-common-divisors-in-linked-list?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/insert-greatest-common-divisors-in-linked-list/',
    slugs: ['insert-greatest-common-divisors-in-linked-list'],
  },
  {
    name: 'Transpose Matrix',
    category: 'Math & Geometry',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/transpose-matrix?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/transpose-matrix',
    slugs: ['transpose-matrix'],
  },
  {
    name: 'Rotate Image',
    category: 'Math & Geometry',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/rotate-matrix?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/rotate-image/',
    slugs: ['rotate-image', 'rotate-matrix'],
  },
  {
    name: 'Spiral Matrix',
    category: 'Math & Geometry',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/spiral-matrix?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/spiral-matrix/',
    slugs: ['spiral-matrix'],
  },
  {
    name: 'Set Matrix Zeroes',
    category: 'Math & Geometry',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/set-zeroes-in-matrix?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/set-matrix-zeroes/',
    slugs: ['set-matrix-zeroes', 'set-zeroes-in-matrix'],
  },
  {
    name: 'Happy Number',
    category: 'Math & Geometry',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/non-cyclical-number?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/happy-number/',
    slugs: ['happy-number', 'non-cyclical-number'],
  },
  {
    name: 'Plus One',
    category: 'Math & Geometry',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/plus-one?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/plus-one/',
    slugs: ['plus-one'],
  },
  {
    name: 'Roman to Integer',
    category: 'Math & Geometry',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/roman-to-integer?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/roman-to-integer/',
    slugs: ['roman-to-integer'],
  },
  {
    name: 'Pow(x, n)',
    category: 'Math & Geometry',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/pow-x-n?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/powx-n/',
    slugs: ['pow-x-n', 'powx-n'],
  },
  {
    name: 'Multiply Strings',
    category: 'Math & Geometry',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/multiply-strings?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/multiply-strings/',
    slugs: ['multiply-strings'],
  },
  {
    name: 'Detect Squares',
    category: 'Math & Geometry',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/count-squares?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/detect-squares/',
    slugs: ['count-squares', 'detect-squares'],
  },
  {
    name: 'Single Number',
    category: 'Bit Manipulation',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/single-number?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/single-number/',
    slugs: ['single-number'],
  },
  {
    name: 'Number of 1 Bits',
    category: 'Bit Manipulation',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/number-of-one-bits?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/number-of-1-bits/',
    slugs: ['number-of-1-bits', 'number-of-one-bits'],
  },
  {
    name: 'Counting Bits',
    category: 'Bit Manipulation',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/counting-bits?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/counting-bits/',
    slugs: ['counting-bits'],
  },
  {
    name: 'Add Binary',
    category: 'Bit Manipulation',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/add-binary?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/add-binary/',
    slugs: ['add-binary'],
  },
  {
    name: 'Reverse Bits',
    category: 'Bit Manipulation',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/reverse-bits?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/reverse-bits/',
    slugs: ['reverse-bits'],
  },
  {
    name: 'Missing Number',
    category: 'Bit Manipulation',
    difficulty: 'Easy',
    url: 'https://neetcode.io/problems/missing-number?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/missing-number/',
    slugs: ['missing-number'],
  },
  {
    name: 'Sum of Two Integers',
    category: 'Bit Manipulation',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/sum-of-two-integers?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/sum-of-two-integers/',
    slugs: ['sum-of-two-integers'],
  },
  {
    name: 'Reverse Integer',
    category: 'Bit Manipulation',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/reverse-integer?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/reverse-integer/',
    slugs: ['reverse-integer'],
  },
  {
    name: 'Bitwise AND of Numbers Range',
    category: 'Bit Manipulation',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/bitwise-and-of-numbers-range?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/bitwise-and-of-numbers-range',
    slugs: ['bitwise-and-of-numbers-range'],
  },
  {
    name: 'Minimum Array End',
    category: 'Bit Manipulation',
    difficulty: 'Medium',
    url: 'https://neetcode.io/problems/minimum-array-end?list=neetcode250',
    leetcodeUrl: 'https://leetcode.com/problems/minimum-array-end/',
    slugs: ['minimum-array-end'],
  },
]

const BY_NAME = new Map(NEETCODE_250.map((p, i) => [p.name.toLowerCase(), i]))

const BY_SLUG = new Map<string, number>()
NEETCODE_250.forEach((p, i) => {
  for (const slug of p.slugs) if (!BY_SLUG.has(slug)) BY_SLUG.set(slug, i)
})

export function findNeetcodeIndex(name: string): number | null {
  const hit = BY_NAME.get(name.trim().toLowerCase())
  return hit === undefined ? null : hit
}

export function findNeetcodeBySlug(slug: string): number | null {
  const hit = BY_SLUG.get(slug.trim().toLowerCase())
  return hit === undefined ? null : hit
}
